import logging
from datetime import datetime
from pathlib import Path
import re
from surge_validation.detiding_validation.config import default_params
import pandas as pd

TIME_COL_NAME = "time"
VALIDH_COL_NAME = "valid_hour"
STID_COL_NAME = "station_id"
LAT_COL_NAME = "lat"
LON_COL_NAME = "lon"
OBS_COL_NAME = "obs"
DATEO_COL_NAME = "dateo"

# indices of the columns in the input file
INFILE_STID_INDEX = 1
INFILE_LAT_INDEX = 2
INFILE_LON_INDEX = 3

SPACE_SEPARATED_XDAT = 1
MODEL_AND_OBS_ONE_FILE = 2

known_formats = [SPACE_SEPARATED_XDAT, MODEL_AND_OBS_ONE_FILE]


def parse_valid_time(tok):
    try:
        return datetime.strptime(tok, "%Y%m%d%H")  # legacy format
    except ValueError:
        return datetime.strptime(tok, "%Y%m%d%H%M")

def read_wl_station_data(data_store, station_dict=None,
                         fname_suffix=".dat",
                         max_lead_hour=None,
                         n_ignore_edge_forecasts:dict = None):
    """
    The data is returned as a pandas dataframe {time, station_id, obs, model1, model2, ... modeln}

    :param n_ignore_edge_forecasts: (n_beg, n_end) - number of first and last forecasts to discard
    :param data_store: if data_store is a folder, look for data files containing station id in their names
    :param station_dict:
    :param format:
    :param fname_suffix:
    """

    logger = logging.getLogger("loadprogs: read_wl_station_data")

    data_store_p = Path(data_store)

    assert data_store_p.exists(), f"{data_store_p} does not exist"

    id_to_data_file = {}

    logging.info(f"Reading {data_store_p} ...")

    df = pd.read_csv(data_store_p, sep=r"\s+", header=None, index_col=False,
                     converters={0: float,
                                 1: str,
                                 2: float, 3: float,
                                 4: parse_valid_time})
    if data_store_p.is_file():

        col_names = [VALIDH_COL_NAME, STID_COL_NAME, LAT_COL_NAME, LON_COL_NAME, TIME_COL_NAME, OBS_COL_NAME, ]

        if len(df.columns) - len(col_names) > 1:
            col_names = col_names + [f"mod{i:03d}" for i in range(len(df.columns) - len(col_names))]
        else:
            col_names = col_names + ["mod", ]

        df.columns = col_names

        df[DATEO_COL_NAME] = (df[TIME_COL_NAME] - pd.TimedeltaIndex((df[VALIDH_COL_NAME] * 3600.).astype(int), unit="seconds"))

        # select only data for selected station ids
        if station_dict is not None:
            logger.info(f"reading only data for specified stations in {station_dict}.")
            select_ids = list(station_dict)
            df = df[df["station_id"].isin(select_ids)]

    elif data_store_p.is_dir():
        for p in data_store_p.iterdir():
            if not p.name.endswith(fname_suffix):
                continue

            d = int(re.findall(r"\d+", p.name)[0])
            id_to_data_file[d] = p

        df_list = []
        for st_id, st_name in station_dict.items():
            df_list.append(get_df_from_space_separated_xdat(id_to_data_file[st_id], st_id))

        df = pd.concat(df_list)
    else:
        raise IOError(f"{data_store}: Does not exist or unknown data store type")

    # filter only lead hour less than the maximum specified
    if max_lead_hour is not None:
        df = df[df[VALIDH_COL_NAME] <= max_lead_hour]

    if n_ignore_edge_forecasts is not None:
        logger.info("Discarding {} first and {} last forecasts, for transients removal")
        to = df[DATEO_COL_NAME]
        to_unique = to.sort_values().drop_duplicates()
        to_min = to_unique.iloc[n_ignore_edge_forecasts["beg"]]
        to_max = to_unique.iloc[len(to_unique) - n_ignore_edge_forecasts["end"] - 1]

        df = df[(to >= to_min) & (to <= to_max)]

    return df


def get_df_from_space_separated_xdat(fpath, station_id):
    data = {TIME_COL_NAME: [], "obs": [], "station_id": []}

    with fpath.open() as f:
        for line in f:
            row = line.split()
            data[TIME_COL_NAME].append(datetime.strptime(f"{row[0]}{row[1]}{row[2]}{row[3]}", "%Y%m%d%H"))

            data["station_id"].append(station_id)

            data["obs"].append(float(row[-1]))

    return pd.DataFrame.from_dict(data)


def get_model_column_names(df, suffix=""):
    return [f"{c}{suffix}" for c in df if c.startswith("mod")]


def get_station_ids(data_path: Path) -> set:
    """
    :return set of station ids found in data_path (text file generated by loadprogs)
    """
    data = read_wl_station_data(data_path)
    return set(data[STID_COL_NAME])


def get_station_id_intersect(data_path_dict: dict) -> set:
    """
    return intersection of station ids available in all the sources
    :param data_path_dict:
    """
    res = None

    for _, pth in data_path_dict.items():
        cur_set = get_station_ids(pth)
        if res is None:
            res = cur_set
        else:
            res = cur_set.intersection(res)

    return res


def read_station_dict_from_obs(obs_files) -> dict:
    """Read station id to name mapping from an obs file or a list of obs files

    Args:
        obs_files (list or single path): 

    Returns:
        dict: mapping {station_id: station_name}
    """
    result = {}
    if isinstance(obs_files, list):
        for obs in obs_files:
            result.update(read_station_dict_from_obs(obs))    
    
    else:
        obs = Path(obs_files)
        assert obs.exists()

        df = pd.read_csv(obs, skiprows=2, sep=r"\s+", converters={"NO": str})

        st_names = df["ID"]
        if "DATA.COUNTRY" in df:
            st_names = st_names + ", " + df["DATA.COUNTRY"]

        return dict(zip(df["NO"], st_names))
